/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author S
 */
public class viewHomeUsers extends javax.swing.JFrame {

    /**
     * Creates new form viewHomeUsers
     */
    public viewHomeUsers() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnObat = new javax.swing.JButton();
        btnPupuk = new javax.swing.JButton();
        btnTanaman = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btm spk obat.png"))); // NOI18N
        btnObat.setBorder(null);
        btnObat.setContentAreaFilled(false);
        getContentPane().add(btnObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 160, 46));

        btnPupuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn spk pupuk.png"))); // NOI18N
        btnPupuk.setBorder(null);
        btnPupuk.setContentAreaFilled(false);
        getContentPane().add(btnPupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 160, 46));

        btnTanaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn spk tanaman.png"))); // NOI18N
        btnTanaman.setBorder(null);
        btnTanaman.setContentAreaFilled(false);
        getContentPane().add(btnTanaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 160, 48));

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn keluar.png"))); // NOI18N
        btnKeluar.setBorder(null);
        btnKeluar.setContentAreaFilled(false);
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 19, 90, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg hal utama.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void addBtnObatListener(ActionListener e) {

        this.btnObat.addActionListener(e);
    }

    public void addBtnPupukListener(ActionListener e) {
        this.btnPupuk.addActionListener(e);
    }

    public void addBtnTanamanListener(ActionListener e) {    
        this.btnTanaman.addActionListener(e);
    }

    public void addBtnKeluarListener(ActionListener e) {
        this.btnKeluar.addActionListener(e);
    }
    
    
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewHomeUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewHomeUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewHomeUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewHomeUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewHomeUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnObat;
    private javax.swing.JButton btnPupuk;
    private javax.swing.JButton btnTanaman;
    // End of variables declaration//GEN-END:variables
}
