/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author S
 */
public class viewSppkPupuk extends javax.swing.JFrame {

    /**
     * Creates new form viewSppkPupuk
     */
    public viewSppkPupuk() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbTanaman = new javax.swing.JComboBox<>();
        cbUsia = new javax.swing.JComboBox<>();
        cbTanah = new javax.swing.JComboBox<>();
        btnCari = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Masukan Kriteria Pupuk");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 170, 33));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Tanaman");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 105, 29));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Tanah");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 105, 26));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Usia Tanaman");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 105, 32));

        cbTanaman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbTanaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 230, 30));

        cbUsia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih tanaman dulu" }));
        getContentPane().add(cbUsia, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 230, 30));

        cbTanah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih tanaman dulu" }));
        getContentPane().add(cbTanah, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 230, 30));

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn submit.png"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.setBorder(null);
        btnCari.setContentAreaFilled(false);
        getContentPane().add(btnCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 110, 30));

        btnBack.setText("Kembali");
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 90, 30));

        logo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, 140));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg hal spk.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addBtnCariListener(ActionListener e) {
        this.btnCari.addActionListener(e);
    }

    public void addCbTanamanListener(ItemListener e) {
        this.cbTanaman.addItemListener(e);
    }

    public JComboBox<String> getCbTanah() {
        return cbTanah;
    }

    public JComboBox<String> getCbTanaman() {
        return cbTanaman;
    }

    public JComboBox<String> getCbUsia() {
        return cbUsia;
    }
    
    public void ShowPupuk(String pupuk) {
        JOptionPane.showMessageDialog(this, "Pupuk yang sesuai adalah "+pupuk);
    }

    public void addBtnBackListener(ActionListener e) {
        this.btnBack.addActionListener(e);
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewSppkPupuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewSppkPupuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewSppkPupuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewSppkPupuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewSppkPupuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCari;
    private javax.swing.JComboBox<String> cbTanah;
    private javax.swing.JComboBox<String> cbTanaman;
    private javax.swing.JComboBox<String> cbUsia;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
