/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author S
 */
public class viewHomeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form viewHomeUsers
     */
    public viewHomeAdmin() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKeluar = new javax.swing.JButton();
        btnKaryawan = new javax.swing.JButton();
        btnListPupuk = new javax.swing.JButton();
        btnListObat = new javax.swing.JButton();
        btnListTanaman = new javax.swing.JButton();
        btnListTanah = new javax.swing.JButton();
        btnListHama = new javax.swing.JButton();
        btnDetailPupuk = new javax.swing.JButton();
        btnDetailTanaman = new javax.swing.JButton();
        btnDetailObat = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn keluar.png"))); // NOI18N
        btnKeluar.setBorder(null);
        btnKeluar.setContentAreaFilled(false);
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 19, 90, 30));

        btnKaryawan.setText("User login  Karyawan");
        getContentPane().add(btnKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 160, -1));

        btnListPupuk.setText("List Pupuk");
        getContentPane().add(btnListPupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 160, -1));

        btnListObat.setText("List Obat");
        getContentPane().add(btnListObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 160, -1));

        btnListTanaman.setText("List Tanaman");
        getContentPane().add(btnListTanaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 160, -1));

        btnListTanah.setText("List Tanah");
        getContentPane().add(btnListTanah, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 160, -1));

        btnListHama.setText("List Hama");
        getContentPane().add(btnListHama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 160, -1));

        btnDetailPupuk.setText("Detail Pupuk");
        getContentPane().add(btnDetailPupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 130, -1));

        btnDetailTanaman.setText("Detail Tanaman");
        getContentPane().add(btnDetailTanaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 130, -1));

        btnDetailObat.setText("Detail Obat");
        getContentPane().add(btnDetailObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 130, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg hal utama.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void addBtnListObatListener(ActionListener e) {

        this.btnListObat.addActionListener(e);
    }

    public void addBtnListPupukListener(ActionListener e) {
        this.btnListPupuk.addActionListener(e);
    }

    public void addBtnListTanamanListener(ActionListener e) {    
        this.btnListTanaman.addActionListener(e);
    }

    public void addBtnKeluarListener(ActionListener e) {
        this.btnKeluar.addActionListener(e);
    }

    public void addBtnDetailObatListener(ActionListener e) {
        this.btnDetailTanaman.addActionListener(e);
    }

    public void addBtnDetailPupukListener(ActionListener e) {
        this.btnDetailPupuk.addActionListener(e);
    }

    public void addBtnKaryawanListener(ActionListener e) {
        this.btnKaryawan.addActionListener(e);
    }

    public void addBtnListHamaListener(ActionListener e) {
        this.btnListHama.addActionListener(e);
    }

    public void addBtnListTanahListener(ActionListener e) {
        this.btnListTanah.addActionListener(e);
    }

    public void addBtnDetailTanamanListener(ActionListener e) {
        this.btnDetailTanaman.addActionListener(e);
    }
    
    
    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewHomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewHomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnDetailObat;
    private javax.swing.JButton btnDetailPupuk;
    private javax.swing.JButton btnDetailTanaman;
    private javax.swing.JButton btnKaryawan;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnListHama;
    private javax.swing.JButton btnListObat;
    private javax.swing.JButton btnListPupuk;
    private javax.swing.JButton btnListTanah;
    private javax.swing.JButton btnListTanaman;
    // End of variables declaration//GEN-END:variables
}
