/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author S
 */
public class viewSppkObat extends javax.swing.JFrame {

    /**
     * Creates new form viewSppkObat
     */
    public viewSppkObat() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbJenisTanaman = new javax.swing.JComboBox<>();
        cbHama = new javax.swing.JComboBox<>();
        cbUsia = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        judul.setForeground(new java.awt.Color(255, 255, 255));
        judul.setText("SPPK Obat");
        getContentPane().add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Jenis Tanaman");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hama");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 70, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usia");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 70, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Masukan Kriteria Obat");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        cbJenisTanaman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbJenisTanaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 210, -1));

        cbHama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih tanaman dulu" }));
        getContentPane().add(cbHama, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 210, -1));

        cbUsia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih tanaman dulu" }));
        getContentPane().add(cbUsia, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 210, -1));

        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btn submit.png"))); // NOI18N
        btnSubmit.setBorder(null);
        btnSubmit.setBorderPainted(false);
        btnSubmit.setContentAreaFilled(false);
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, -1, -1));

        btnBack.setText("Kembali");
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 70, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg hal spk.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JComboBox<String> getCbHama() {
        return cbHama;
    }

    public JComboBox<String> getCbUsia() {
        return cbUsia;
    }

    public JComboBox<String> getCbJenisTanaman() {
        return cbJenisTanaman;
    }

    public void addBtnBackListener(ActionListener e) {
        this.btnBack.addActionListener(e);
    }

    public void addBtnSubmitListener(ActionListener e) {
        this.btnSubmit.addActionListener(e);
    }

    public void addCbJenisTanamanListener(ItemListener e) {
        this.cbJenisTanaman.addItemListener(e);
    }
    
    

    /**
     * @param args the command line arguments
     */
    
    
    
    public void ShowObat(String obat) {
        JOptionPane.showMessageDialog(this, "Obat yang sesuai adalah "+obat);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewSppkObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewSppkObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewSppkObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewSppkObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewSppkObat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbHama;
    private javax.swing.JComboBox<String> cbJenisTanaman;
    private javax.swing.JComboBox<String> cbUsia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
